openapi: 3.1.0
info:
  title: User API
  description: Simple API demonstrating how to use JSON Schema in an OpenAPI 3.1.0 specification and inside of a Node.JS backend.
  version: 1.0.0
  contact:
    name: Sebastian Abshoff
    email: s.abshoff@reply.de
servers:
  - url: 'http://localhost:8000'
    description: local server
paths:
  /welcome:
    post:
      operationId: welcomeUser
      description: welcomes a user
      tags:
        - user
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./replyer.json
            examples:
              j.doe:
                value:
                  username: j.doe
                  forename: John
                  surname: Doe
                  location: Gütersloh
        description: 'A JSON file providing username, forename, surename and location'
tags:
  - name: user
    description: User API
